services:
  app:
    build:
      context: ..
      dockerfile: lab-1/Dockerfile
    restart: unless-stopped
    environment:
      - ENV=${ENV:-dev}
      - SERVER_TYPE=tcp
      - PORT=8080
    # NOTE(koftamainee): server can be running via TCP or HTTP so no healthcheck
    ports:
      - "127.0.0.1:8080:8080"
